package Solved;


/**
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?   
   
**/


import java.math.*;
public class doce{
    public void calcularNumeroTriangular(int numeroTriangular){
        System.gc();
        int c=1;
        int triangular;
        triangular= (numeroTriangular*(numeroTriangular+1))/2;
        while(true){
            
            for(int i=1;i<=(triangular/2)+1;i++){
                if(triangular%i==0){
                    c++;
                }
            }
            if(c>=499 || numeroTriangular%13000==0){
                 System.out.println("El numero triangular n."+numeroTriangular+" es:"
                +triangular+" y tiene mas de "+c+" divisores");
                System.exit(0);
                //break
            }else{
                System.out.print(c<10 ? "\n"+numeroTriangular+" c:"+c+"   tr:"+triangular:"");
                System.out.print(c>=10 && c<100 ? "\n"+numeroTriangular+" c:"+c+"  tr:"+triangular:"");
                System.out.print(c>=100 ? "\n"+numeroTriangular+" c:"+c+" tr:"+triangular:"");
                //System.out.println(numeroTriangular+" c:"+c+" tr"+triangular);
                numeroTriangular++;
                triangular+=numeroTriangular;
                c=1;
                
            }
        }

    }

    //Triangular Number
    public static void main(String[] args){
        doce d = new doce();
        d.calcularNumeroTriangular(12350);
        //12374


    }
}
