package Solved;


/**
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
 */
import java.math.BigInteger;
public class fortyfivev2
{
    public static void main(String[] args){
        long number=286;

        while(true){
            long T= (long)number*(number+1)/2; //T= n(n+1) /2   ---> 1/2*(sqrt(8*T+1)-1)
            long P = 0;//Pn=n(3n−1)/2   ----> 1/6*(sqrt(24*P+1)+1)
            long H = 0;   //Hn=n(2n−1)    ----->1/4*(sqrt(8*H+1)+1)
            for(int i = (int)number-100; i>0;i--){
                P= (long)i*(3*i-1)/2L;
                //System.out.println("t:"+T.toString()+" p:"+P.toString()+" i:"+i +" n:"+ number);
                if(P<T){
                    //System.out.println("t:"+T.toString()+" p:"+P.toString()+" i:"+i +" n:"+ number);
                    break;
                }
                if(P==T){
                    
                    System.out.println("t:"+T+" p:"+P+" i:"+i +" n:"+ number);
                    //System.exit(0);
                    for(int j=i-10;j>0;j--){
                        H= (long)(j*(2*j-1));
                        if(H<P){
                            //System.out.println("t:"+T.toString()+" p:"+P.toString()+" i:"+i +" n:"+ number);
                            break;
                        }
                        if(H==P){
                            
                            System.out.println("t:"+T+" p:"+P+" h:"+H+" i:"+i +" j:"+j+" n:"+ number);
                            System.exit(0);
                            
                        }
                    }
                                  
                }

            }
            number++;
             System.out.print(number%1000==0 ?"\n"+ T+" "+P+" "+H +" "+ number:"");
            if(number%100000==0 ){
                System.out.println(T+" "+P+" "+H +" "+ number);
                break;
            }
        }
    }
    //46342
}
