package Solved;


/**Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.**/
import java.math.*;
public class two
{
    public static void main(String[] args){
        //n= n-1 + n-2
        //suma = number + aux;
        int aux=0;
        int number=1;
        int suma=0;
        int sumapar=0;
        System.out.println("");
        for(int i=0;i<4000000;i++){
            if(sumapar>4000000){

                System.out.println("Suma par:"+sumapar);
                System.out.println("Suma normal:"+suma);
                break;
            }
            if((number)%2==0){
                sumapar+=number;
            }
            suma=number+aux;
            System.out.print(suma%10==0 ? "suma:"+suma+",sumapar:"+sumapar+"\n ": "s:"+suma+",sp:"+sumapar);
            aux=number;
            number=suma;
        }

    }

}